### ISSUE TITLE
AttributeError: 'EnumTypeWrapper' object has no attribute 'RKE_ACTION_LOCK'

### ISSUE THREAD

**Issue by BogdanDIA** [kaedenbrinkman/PyTeslaBLE#9]
Hi,

I tried today sending one command to my car over BLE. I am using Ubuntu 20.04.
After replacing the .write_command to .write_request wherever needed, the execution went almost to the end except the last write, see below. Can this be due to wrong VCSEC? : 

...
Enter choice: 1
Connecting to vehicle...
Enter a command, or 'help' for a list of commands. Type 'exit' to quit.
Enter command: help

Commands available:
	EXIT: Exit the program
	HELP: Print this message
	LOCK: Lock the vehicle
	UNLOCK: Unlock the vehicle
	OPEN_TRUNK: Open the vehicle's trunk
	OPEN_FRUNK: Open the vehicle's front trunk
	OPEN_CHARGE_PORT: Open and unlock the vehicle's charge port
	CLOSE_CHARGE_PORT: Close and lock the vehicle's charge port

Enter a command, or 'help' for a list of commands. Type 'exit' to quit.
Enter command: LOCK
Traceback (most recent call last):
  File "Main.py", line 42, in <module>
    vehicle.lock()
  File "/home/account/.local/lib/python3.8/site-packages/pyteslable/TeslaBLE.py", line 254, in lock
    msg = self.__service.lockMsg()
  File "/home/account/.local/lib/python3.8/site-packages/pyteslable/TeslaBLE.py", line 473, in lockMsg
    return self.rkeActionMsg(VCSEC_pb2.RKEAction_E.RKE_ACTION_LOCK)
AttributeError: 'EnumTypeWrapper' object has no attribute 'RKE_ACTION_LOCK'

Thanks

**Comment by BogdanDIA** [comment]
Answering to my own question now. The protobuf EnumTypeWrapper has now tho methods Name() and Value() so all the calls in TeslaBLE.py need to change from:

def unlockMsg(self):
        return self.rkeActionMsg(VCSEC_pb2.RKEAction_E.RKE_ACTION_UNLOCK))

to:

def unlockMsg(self):
        return self.rkeActionMsg(VCSEC_pb2.RKEAction_E.Value('RKE_ACTION_UNLOCK'))
